name: "Acceptance Tests"

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  behat-domain:
    name: "Behat - Domain"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Cancel Previous Runs"
        uses: "styfle/cancel-workflow-action@0.4.0"
        with:
          access_token: ${{ github.token }}

      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: '7.4'
          extensions: intl, zip, zlib
          coverage: none
          ini-values: memory_limit=-1

      - name: "Setup Composer Cache"
        uses: "actions/cache@v2"
        with:
          path: |
            ~/.composer/cache
            vendor
            bin
            app/etc/db_schema.xml
            app/etc/di.xml
            app/etc/NonComposerComponentRegistration.php
            app/etc/registration_globlist.php
            app/etc/vendor_path.php
            app/autoload.php
            app/bootstrap.php
            app/functions.php
            setup
          key: "php-7.2-composer-locked"
          restore-keys: "php-7.2-composer-locked"

      - name: "Setup Composer Auth"
        run: "echo $COMPOSER_AUTH_JSON > auth.json"
        env:
          COMPOSER_AUTH_JSON: ${{ secrets.COMPOSER_AUTH_JSON }}

      - name: "Install Project Dependencies"
        run: "composer install --prefer-dist --no-interaction --no-progress --no-suggest"

      - name: "Run behat"
        run: "bin/behat --suite=domain --no-interaction --no-snippets --stop-on-failure --format=pretty"

  behat-application:
    name: "Behat - Application"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Cancel Previous Runs"
        uses: "styfle/cancel-workflow-action@0.4.0"
        with:
          access_token: ${{ github.token }}

      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: '7.4'
          extensions: intl, zip, zlib
          coverage: none
          ini-values: memory_limit=-1

      - name: "Setup Composer Cache"
        uses: "actions/cache@v2"
        with:
          path: |
            ~/.composer/cache
            vendor
            bin
            app/etc/db_schema.xml
            app/etc/di.xml
            app/etc/NonComposerComponentRegistration.php
            app/etc/registration_globlist.php
            app/etc/vendor_path.php
            app/autoload.php
            app/bootstrap.php
            app/functions.php
            setup
          key: "php-7.2-composer-locked"
          restore-keys: "php-7.2-composer-locked"

      - name: "Setup Composer Auth"
        run: "echo $COMPOSER_AUTH_JSON > auth.json"
        env:
          COMPOSER_AUTH_JSON: ${{ secrets.COMPOSER_AUTH_JSON }}

      - name: "Install Project Dependencies"
        run: "composer install --prefer-dist --no-interaction --no-progress --no-suggest"

      - name: "Run behat"
        run: "bin/behat --suite=application --no-interaction --no-snippets --stop-on-failure --format=pretty"

  behat-integration:
    name: "Behat - Integration"

    runs-on: "ubuntu-latest"

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: magento
          MYSQL_PASSWORD: magento
          MYSQL_DATABASE: magento
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: "Cancel Previous Runs"
        uses: "styfle/cancel-workflow-action@0.4.0"
        with:
          access_token: ${{ github.token }}

      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: '7.4'
          extensions: intl, zip, zlib
          coverage: none
          ini-values: memory_limit=-1

      - name: "Setup Composer Cache"
        uses: "actions/cache@v2"
        with:
          path: |
            ~/.composer/cache
            vendor
            bin
            app/etc/db_schema.xml
            app/etc/di.xml
            app/etc/NonComposerComponentRegistration.php
            app/etc/registration_globlist.php
            app/etc/vendor_path.php
            app/autoload.php
            app/bootstrap.php
            app/functions.php
            setup
          key: "php-7.2-composer-locked"
          restore-keys: "php-7.2-composer-locked"

      - name: "Setup Composer Auth"
        run: "echo $COMPOSER_AUTH_JSON > auth.json"
        env:
          COMPOSER_AUTH_JSON: ${{ secrets.COMPOSER_AUTH_JSON }}

      - name: "Install Project Dependencies"
        run: "composer install --prefer-dist --no-interaction --no-progress --no-suggest"

      - name: "Install Magento"
        run: |
          mkdir -p pub/static pub/media
          bin/magento setup:install --admin-email "kotosy.magento@gmail.com" --admin-firstname "admin" --admin-lastname "admin" --admin-password "admin123" --admin-user "admin" --backend-frontname admin --base-url "http://magento.test" --db-host 127.0.0.1 --db-name magento --db-user magento --db-password magento --session-save files --use-rewrites 1 --use-secure 0 -vvv
          bin/magento setup:upgrade

      - name: "Run behat"
        run: "bin/behat --suite=integration --no-interaction --no-snippets --stop-on-failure --format=pretty"

  behat-end-to-end:
    name: "Behat - End to End"

    runs-on: "ubuntu-latest"

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: magento
          MYSQL_PASSWORD: magento
          MYSQL_DATABASE: magento
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: "Cancel Previous Runs"
        uses: "styfle/cancel-workflow-action@0.4.0"
        with:
          access_token: ${{ github.token }}

      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: '7.4'
          extensions: intl, zip, zlib
          coverage: none
          ini-values: memory_limit=-1

      - name: "Setup Composer Cache"
        uses: "actions/cache@v2"
        with:
          path: |
            ~/.composer/cache
            vendor
            bin
            app/etc/db_schema.xml
            app/etc/di.xml
            app/etc/NonComposerComponentRegistration.php
            app/etc/registration_globlist.php
            app/etc/vendor_path.php
            app/autoload.php
            app/bootstrap.php
            app/functions.php
            setup
          key: "php-7.2-composer-locked"
          restore-keys: "php-7.2-composer-locked"

      - name: "Setup Composer Auth"
        run: "echo $COMPOSER_AUTH_JSON > auth.json"
        env:
          COMPOSER_AUTH_JSON: ${{ secrets.COMPOSER_AUTH_JSON }}

      - name: "Install Project Dependencies"
        run: "composer install --prefer-dist --no-interaction --no-progress --no-suggest"

      - name: "Install Magento"
        run: |
          mkdir -p pub/static pub/media
          bin/magento setup:install --admin-email "kotosy.magento@gmail.com" --admin-firstname "admin" --admin-lastname "admin" --admin-password "admin123" --admin-user "admin" --backend-frontname admin --base-url "http://magento.test" --db-host 127.0.0.1 --db-name magento --db-user magento --db-password magento --session-save files --use-rewrites 1 --use-secure 0 -vvv
          bin/magento setup:upgrade

      - name: "Run behat"
        run: "bin/behat --suite=endtoend --no-interaction --no-snippets --stop-on-failure --format=pretty"
