name: "Quality Checks"

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  phplint:
    name: "PHP Lint"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Cancel Previous Runs"
        uses: "styfle/cancel-workflow-action@0.4.0"
        with:
          access_token: ${{ github.token }}

      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: '7.2'
          extensions: intl, zip, zlib
          coverage: none
          ini-values: memory_limit=-1

      - name: "Run php -l"
        run: find src/ -type f \( -name '*.phtml' -o -name '*.php' \) | xargs -n 1 -P 8 -i php -l {} | grep -v 'No syntax errors detected' || echo 'OK'

  phpcs:
    name: "PHP Code Sniffer"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Cancel Previous Runs"
        uses: "styfle/cancel-workflow-action@0.4.0"
        with:
          access_token: ${{ github.token }}

      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: '7.2'
          extensions: intl, zip, zlib
          coverage: none
          ini-values: memory_limit=-1

      - name: "Setup Composer Cache"
        uses: "actions/cache@v2"
        with:
          path: |
            ~/.composer/cache
            vendor
            bin
            app/etc/db_schema.xml
            app/etc/di.xml
            app/etc/NonComposerComponentRegistration.php
            app/etc/registration_globlist.php
            app/etc/vendor_path.php
            app/autoload.php
            app/bootstrap.php
            app/functions.php
            setup
          key: "php-7.2-composer-locked"
          restore-keys: "php-7.2-composer-locked"

      - name: "Setup Composer Auth"
        run: "echo $COMPOSER_AUTH_JSON > auth.json"
        env:
          COMPOSER_AUTH_JSON: ${{ secrets.COMPOSER_AUTH_JSON }}

      - name: "Install Project Dependencies"
        run: "composer install --prefer-dist --no-interaction --no-progress --no-suggest"

      - name: "Run phpcs"
        run: "bin/phpcs -p"

  phpcpd:
    name: "PHP Copy/Paste Detector"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Cancel Previous Runs"
        uses: "styfle/cancel-workflow-action@0.4.0"
        with:
          access_token: ${{ github.token }}

      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: '7.2'
          extensions: intl, zip, zlib
          coverage: none
          ini-values: memory_limit=-1

      - name: "Setup Composer Cache"
        uses: "actions/cache@v2"
        with:
          path: |
            ~/.composer/cache
            vendor
            bin
            app/etc/db_schema.xml
            app/etc/di.xml
            app/etc/NonComposerComponentRegistration.php
            app/etc/registration_globlist.php
            app/etc/vendor_path.php
            app/autoload.php
            app/bootstrap.php
            app/functions.php
            setup
          key: "php-7.2-composer-locked"
          restore-keys: "php-7.2-composer-locked"

      - name: "Setup Composer Auth"
        run: "echo $COMPOSER_AUTH_JSON > auth.json"
        env:
          COMPOSER_AUTH_JSON: ${{ secrets.COMPOSER_AUTH_JSON }}

      - name: "Install Project Dependencies"
        run: "composer install --prefer-dist --no-interaction --no-progress --no-suggest"

      - name: "Run phpcpd"
        run: "bin/phpcpd --progress src"

  psalm:
    name: "Psalm"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Cancel Previous Runs"
        uses: "styfle/cancel-workflow-action@0.4.0"
        with:
          access_token: ${{ github.token }}

      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: '7.2'
          extensions: intl, zip, zlib
          coverage: none
          ini-values: memory_limit=-1

      - name: "Setup Composer Cache"
        uses: "actions/cache@v2"
        with:
          path: |
            ~/.composer/cache
            vendor
            bin
            app/etc/db_schema.xml
            app/etc/di.xml
            app/etc/NonComposerComponentRegistration.php
            app/etc/registration_globlist.php
            app/etc/vendor_path.php
            app/autoload.php
            app/bootstrap.php
            app/functions.php
            setup
          key: "php-7.2-composer-locked"
          restore-keys: "php-7.2-composer-locked"

      - name: "Setup Composer Auth"
        run: "echo $COMPOSER_AUTH_JSON > auth.json"
        env:
          COMPOSER_AUTH_JSON: ${{ secrets.COMPOSER_AUTH_JSON }}

      - name: "Install Project Dependencies"
        run: "composer install --prefer-dist --no-interaction --no-progress --no-suggest"

      - name: "Generate auto-generated classes"
        run: "bin/magento setup:di:compile"

      - name: "Run psalm"
        run: "bin/psalm --output-format=github"

  phpstan:
    name: "PhpStan"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Cancel Previous Runs"
        uses: "styfle/cancel-workflow-action@0.4.0"
        with:
          access_token: ${{ github.token }}

      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: '7.2'
          extensions: intl, zip, zlib
          coverage: none
          ini-values: memory_limit=-1

      - name: "Setup Composer Cache"
        uses: "actions/cache@v2"
        with:
          path: |
            ~/.composer/cache
            vendor
            bin
            app/etc/db_schema.xml
            app/etc/di.xml
            app/etc/NonComposerComponentRegistration.php
            app/etc/registration_globlist.php
            app/etc/vendor_path.php
            app/autoload.php
            app/bootstrap.php
            app/functions.php
            setup
          key: "php-7.2-composer-locked"
          restore-keys: "php-7.2-composer-locked"

      - name: "Setup Composer Auth"
        run: "echo $COMPOSER_AUTH_JSON > auth.json"
        env:
          COMPOSER_AUTH_JSON: ${{ secrets.COMPOSER_AUTH_JSON }}

      - name: "Install Project Dependencies"
        run: "composer install --prefer-dist --no-interaction --no-progress --no-suggest"

      - name: "Generate auto-generated classes"
        run: "bin/magento setup:di:compile"

      - name: "Run phpstan"
        run: "bin/phpstan analyse --error-format github"

  phpmd:
    name: "PHP Mess Detector"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Cancel Previous Runs"
        uses: "styfle/cancel-workflow-action@0.4.0"
        with:
          access_token: ${{ github.token }}

      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: '7.2'
          extensions: intl, zip, zlib
          coverage: none
          ini-values: memory_limit=-1

      - name: "Setup Composer Cache"
        uses: "actions/cache@v2"
        with:
          path: |
            ~/.composer/cache
            vendor
            bin
            app/etc/db_schema.xml
            app/etc/di.xml
            app/etc/NonComposerComponentRegistration.php
            app/etc/registration_globlist.php
            app/etc/vendor_path.php
            app/autoload.php
            app/bootstrap.php
            app/functions.php
            setup
          key: "php-7.2-composer-locked"
          restore-keys: "php-7.2-composer-locked"

      - name: "Setup Composer Auth"
        run: "echo $COMPOSER_AUTH_JSON > auth.json"
        env:
          COMPOSER_AUTH_JSON: ${{ secrets.COMPOSER_AUTH_JSON }}

      - name: "Install Project Dependencies"
        run: "composer install --prefer-dist --no-interaction --no-progress --no-suggest"

      - name: "Run phpmd"
        run: "bin/phpmd ./src text ./phpmd.xml"

  deptrac:
    name: "Deptrac"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Cancel Previous Runs"
        uses: "styfle/cancel-workflow-action@0.4.0"
        with:
          access_token: ${{ github.token }}

      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: '7.2'
          extensions: intl, zip, zlib
          coverage: none
          ini-values: memory_limit=-1

      - name: "Setup Composer Cache"
        uses: "actions/cache@v2"
        with:
          path: |
            ~/.composer/cache
            vendor
            bin
            app/etc/db_schema.xml
            app/etc/di.xml
            app/etc/NonComposerComponentRegistration.php
            app/etc/registration_globlist.php
            app/etc/vendor_path.php
            app/autoload.php
            app/bootstrap.php
            app/functions.php
            setup
          key: "php-7.2-composer-locked"
          restore-keys: "php-7.2-composer-locked"

      - name: "Setup Composer Auth"
        run: "echo $COMPOSER_AUTH_JSON > auth.json"
        env:
          COMPOSER_AUTH_JSON: ${{ secrets.COMPOSER_AUTH_JSON }}

      - name: "Install Project Dependencies"
        run: "composer install --prefer-dist --no-interaction --no-progress --no-suggest"

      - name: "Run deptrac"
        run: "bin/deptrac --formatter-github-actions=true"
