name: "Security Checks"

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  sensiolabs-security-checker:
    name: "SensioLabs Security Checker"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Cancel Previous Runs"
        uses: "styfle/cancel-workflow-action@0.4.0"
        with:
          access_token: ${{ github.token }}

      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: PHP Security Checker
        uses: StephaneBour/actions-php-security-checker@1.0
        with:
          composer-lock: './composer-lock'
