name: "Testing docker stuff"

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  foobar:
    name: "Foobar"

    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: true

    container:
        image: tkotosz/magento2-bdd-example-console:latest

    services:
        database:
          image: mysql:8.0
          options: >-
            --default-authentication-plugin=mysql_native_password
            --log_bin_trust_function_creators=1
            --max_allowed_packet=4M
          env:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: magento
            MYSQL_PASSWORD: magento
            MYSQL_DATABASE: magentodb
          ports:
            - 3306:3306

        elasticsearch:
          image: elasticsearch:7.12.1
          environment:
            ES_JAVA_OPTS: -Xms512m -Xmx512m
            discovery.type: single-node
          ports:
            - 9200:9200

        redis-cache:
          image: redis:6
          options: >-
            --maxmemory 1073742000
            --maxmemory-policy allkeys-lru
            --save 3600 1
            --save 300 100
            --save 60 10000
          ports:
            - 6379:6379

        redis-session:
          image: redis:6
          options: >-
            --maxmemory 1073742000
            --maxmemory-policy volatile-ttl
            --save 3600 1
            --save 300 100
            --save 60 10000

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Setup Composer Auth"
        run: "echo $COMPOSER_AUTH_JSON > auth.json"
        env:
          COMPOSER_AUTH_JSON: ${{ secrets.COMPOSER_AUTH_JSON }}

      - name: Install magento
        run: |
          ls -lah
          composer install --prefer-dist --no-interaction
          bin/magento setup:install --admin-email "foobar@gmail.com" --admin-firstname "admin" --admin-lastname "admin" --admin-password "admin123" --admin-user "admin" --backend-frontname "admin" --base-url "https://docker-test-project.local/" --use-rewrites 1 --use-secure 1 --db-host "database" --db-name "magentodb" --db-user "magento" --db-password "magento" --session-save "redis" --session-save-redis-host "redis-session" --session-save-redis-port 6379 --session-save-redis-db 1 --cache-backend "redis" --cache-backend-redis-server "redis-cache" --cache-backend-redis-port 6379 --cache-backend-redis-db 2 --page-cache "redis" --page-cache-redis-server "redis-cache" --page-cache-redis-port 6379 --page-cache-redis-db 3 --search-engine "elasticsearch7" --elasticsearch-host "elasticsearch" --elasticsearch-port 9200 --amqp-host "rabbitmq" --amqp-port 5672 --amqp-user "rabbit_magento" --amqp-password "rabbit_magento" --amqp-virtualhost "rabbit_magento" --http-cache-hosts "varnish:80"
          bin/magento setup:upgrade
          bin/magento config:set --scope=default --scope-code=0 system/full_page_cache/caching_application 2
          bin/magento cache:clean

      - name: "Run behat"
        run: "bin/behat --suite=endtoend --no-interaction --no-snippets --stop-on-failure --format=pretty"
