name: "Testing docker stuff"

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  foobar:
    name: "Foobar"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: Compose up
        run: docker-compose up -d

      - name: Check running containers
        run: docker-compose ps

      - name: "Setup Composer Auth"
        run: "echo $COMPOSER_AUTH_JSON > auth.json"
        env:
          COMPOSER_AUTH_JSON: ${{ secrets.COMPOSER_AUTH_JSON }}

      - name: Install magento
        run: |
          docker-compose exec -T console mkdir -p pub/static pub/media
          docker-compose exec -T console composer install --prefer-dist --no-interaction --no-progress --no-suggest
          docker-compose exec -T console bin/magento setup:install --admin-email "foobar@gmail.com" --admin-firstname "admin" --admin-lastname "admin" --admin-password "admin123" --admin-user "admin" --backend-frontname "admin" --base-url "https://docker-test-project.local/" --use-rewrites 1 --use-secure 1 --db-host "database" --db-name "magentodb" --db-user "magento" --db-password "magento" --session-save "redis" --session-save-redis-host "redis-session" --session-save-redis-port 6379 --session-save-redis-db 1 --cache-backend "redis" --cache-backend-redis-server "redis-cache" --cache-backend-redis-port 6379 --cache-backend-redis-db 2 --page-cache "redis" --page-cache-redis-server "redis-cache" --page-cache-redis-port 6379 --page-cache-redis-db 3 --search-engine "elasticsearch7" --elasticsearch-host "elasticsearch" --elasticsearch-port 9200 --amqp-host "rabbitmq" --amqp-port 5672 --amqp-user "rabbit_magento" --amqp-password "rabbit_magento" --amqp-virtualhost "rabbit_magento" --http-cache-hosts "varnish:80"
          docker-compose exec -T console bin/magento setup:upgrade
          docker-compose exec -T console bin/magento config:set --scope=default --scope-code=0 system/full_page_cache/caching_application 2
          docker-compose exec -T console bin/magento cache:clean

      - name: "Run behat"
        run: "docker-compose exec -T console bin/behat --suite=endtoend --no-interaction --no-snippets --stop-on-failure --format=pretty"

      - name: Compose down
        run: docker-compose down
